
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Mar 10 22:32:38 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SRBRACE = 50;
  public static final int CONST = 4;
  public static final int CHAR = 6;
  public static final int GE = 27;
  public static final int CASE = 11;
  public static final int SEMI = 51;
  public static final int LPAREN = 45;
  public static final int CONTINUE = 20;
  public static final int INT = 5;
  public static final int FOR = 23;
  public static final int MINUS = 33;
  public static final int RPAREN = 46;
  public static final int AND = 41;
  public static final int DOUBLE_INC = 38;
  public static final int LT = 28;
  public static final int OR = 42;
  public static final int COMMA = 52;
  public static final int BOOL = 7;
  public static final int INC = 30;
  public static final int DIV = 35;
  public static final int PLUS = 32;
  public static final int MAIN = 3;
  public static final int IF = 17;
  public static final int CARET = 40;
  public static final int DOT = 39;
  public static final int LE = 26;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int EQUAL = 36;
  public static final int NEW = 10;
  public static final int error = 1;
  public static final int MUL = 34;
  public static final int NUMBER = 56;
  public static final int MOD = 37;
  public static final int IDENT = 55;
  public static final int BREAK = 19;
  public static final int VOID = 8;
  public static final int EQ = 24;
  public static final int SWITCH = 21;
  public static final int COLON = 44;
  public static final int LBRACE = 47;
  public static final int ELSE = 18;
  public static final int ENUM = 9;
  public static final int READ = 14;
  public static final int GOTO = 22;
  public static final int CHARCONST = 54;
  public static final int RBRACE = 48;
  public static final int FULLSTOP = 53;
  public static final int BOOLCONST = 16;
  public static final int PROG = 2;
  public static final int NE = 25;
  public static final int QUESTION = 43;
  public static final int DEC = 31;
  public static final int SLBRACE = 49;
  public static final int GT = 29;
  public static final int PRINT = 12;
  public static final int LENGTH = 15;
}

